package tz.go.bukobamc.meetings.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import tz.go.bukobamc.meetings.model.*;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Objects;

@Service
public class MeetingReportService {
    private static final Color GREEN = new Color(8, 127, 69);
    private static final Color GOLD = new Color(215, 169, 0);
    private static final Color SKY = new Color(65, 143, 222);
    private static final Color INK = new Color(22, 34, 27);
    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");

    public byte[] buildPdf(Meeting meeting, List<Guest> guestList,
                           List<Invitation> invitations, List<AttendanceRecord> attendance) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            Document doc = new Document(PageSize.A4.rotate(), 36, 36, 48, 36);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, INK);
            Font subFont = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(102, 116, 107));
            Font headFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE);
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9, INK);

            Paragraph council = new Paragraph("BUKOBA MUNICIPAL COUNCIL", titleFont);
            council.setSpacingAfter(2);
            doc.add(council);
            Paragraph subtitle = new Paragraph("Meeting Attendance Report", subFont);
            subtitle.setSpacingAfter(12);
            doc.add(subtitle);

            PdfPTable meta = new PdfPTable(2);
            meta.setWidthPercentage(100);
            meta.setSpacingAfter(14);
            addMetaRow(meta, "Reference", meeting.reference, cellFont);
            addMetaRow(meta, "Title", meeting.title, cellFont);
            addMetaRow(meta, "Schedule",
                meeting.startAt.format(DT) + " – " + meeting.endAt.format(DT), cellFont);
            addMetaRow(meta, "Location", Objects.toString(meeting.location, "—"), cellFont);
            addMetaRow(meta, "Department", Objects.toString(meeting.department, "—"), cellFont);
            addMetaRow(meta, "Status", Objects.toString(meeting.status, "draft"), cellFont);
            doc.add(meta);

            long attended = guestList.stream()
                .filter(g -> attendance.stream()
                    .anyMatch(a -> Objects.equals(a.participantId, g.id) && a.used))
                .count();

            Paragraph summary = new Paragraph(
                "Invited: " + guestList.size() + "   |   Attended: " + attended
                    + "   |   Attendance rate: "
                    + (guestList.isEmpty() ? "0" : Math.round(attended * 10000.0 / guestList.size()) / 100.0) + "%",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, GREEN));
            summary.setSpacingAfter(10);
            doc.add(summary);

            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);
            String[] headers = {"Name", "Phone", "Email", "Organisation", "RSVP", "Attendance", "Check-in"};
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, headFont));
                cell.setBackgroundColor(GREEN);
                cell.setPadding(6);
                table.addCell(cell);
            }
            for (Guest g : guestList) {
                Invitation inv = invitations.stream()
                    .filter(i -> Objects.equals(i.guest.id, g.id)).findFirst().orElse(null);
                AttendanceRecord att = attendance.stream()
                    .filter(a -> Objects.equals(a.participantId, g.id) && a.used).findFirst().orElse(null);
                String rsvp = inv != null && inv.response != null ? inv.response.status : "no_response";
                table.addCell(cell(g.name, cellFont));
                table.addCell(cell(Objects.toString(g.phone, ""), cellFont));
                table.addCell(cell(Objects.toString(g.email, ""), cellFont));
                table.addCell(cell(Objects.toString(g.organization, ""), cellFont));
                table.addCell(cell(rsvp, cellFont));
                table.addCell(cell(att != null ? "attended" : "not_attended", cellFont));
                table.addCell(cell(att != null ? att.signedInAt.format(DT) : "", cellFont));
            }
            doc.add(table);

            Paragraph footer = new Paragraph(
                "Generated by BMC Meeting Management System • Official council record",
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, SKY));
            footer.setSpacingBefore(16);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new IllegalStateException("PDF generation failed", e);
        }
    }

    private static void addMetaRow(PdfPTable table, String label, String value, Font font) {
        PdfPCell l = new PdfPCell(new Phrase(label, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, INK)));
        l.setBorder(Rectangle.NO_BORDER);
        l.setPadding(4);
        PdfPCell v = new PdfPCell(new Phrase(value, font));
        v.setBorder(Rectangle.NO_BORDER);
        v.setPadding(4);
        table.addCell(l);
        table.addCell(v);
    }

    private static PdfPCell cell(String text, Font font) {
        PdfPCell c = new PdfPCell(new Phrase(text == null ? "" : text, font));
        c.setPadding(5);
        return c;
    }
}
